In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from itertools import combinations
from collections import Counter

In [2]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
236,tt2319580,12700000,3430018,The Grand Seduction,Brendan Gleeson|Taylor Kitsch|Gordon Pinsent|L...,Don McKellar,The small town of Tickle Cove needed a doctor....,A small fishing village must procure a local d...,112,Comedy,Max Films Productions|Morag Loves Company,5/30/2014,6.7,2014
451,tt1322312,32000000,42045846,Going the Distance,Drew Barrymore|Justin Long|Christina Applegate...,Nanette Burstein,A comedy about meeting each other halfway.,Erin and Garrett are very much in love. When E...,102,Comedy|Drama|Romance,New Line Cinema|Offspring Entertainment,9/1/2010,6.0,2010
146,tt1528100,140000000,268031828,Exodus: Gods and Kings,Christian Bale|Joel Edgerton|John Turturro|Aar...,Ridley Scott,"Once brothers, now enemies.",The defiant leader Moses rises up against the ...,153,Adventure|Drama|Action,Scott Free Productions|Chernin Entertainment|B...,12/3/2014,5.6,2014
1829,tt0208003,30000000,173959438,Big Momma's House,Martin Lawrence|Nia Long|Paul Giamatti|Jascha ...,Raja Gosnell,This FBI agent is going undercover... and he's...,When a street-smart FBI agent is sent to Georg...,98,Crime|Comedy,Twentieth Century Fox Film Corporation|Regency...,5/31/2000,5.7,2000
1657,tt0349825,28000000,64445708,Miracle,Kurt Russell|Patricia Clarkson|Noah Emmerich|S...,Gavin O'Connor,"If you believe in yourself, anything can happen.","In 1980, the United States Ice Hockey team's c...",135,Drama|History,Walt Disney,2/6/2004,6.8,2004

In [3]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [4]:
answers = {} # создадим словарь для ответов

In [5]:
def func_split(string):         # функция для преобразования строки с разделителем "|" в список
    return string.split('|')


def func_date(string):         # функция для преобразования строки с разделителем "\" в список
    return string.split('/')


data['profit'] = data['revenue'] - data['budget'] # добавим столбец прибыли

# Ниже добавим колонки, которые будут содержать в себе преобразованные в список данные
data['list_of_cast'] = data.cast.apply(func_split) 

data['list_of_genres'] = data.genres.apply(func_split) 

data['list_of_director'] = data.director.apply(func_split)

data['list_of_production_companies'] = data.production_companies.apply(func_split)

data['release_month'] = data.release_date.apply(func_date) #колонка месяца выхода фильма
data['release_month'] = data.release_month\
.apply(lambda x: int(x[0])) # преобразуем формат str в int

# добавим столбец с длиной названий фильмов
data['title_length'] = data.original_title.apply(lambda title: len(title))
# добавим столбец с длиной описания к фильму
data['overview_length'] = data.overview.apply(lambda overview: len(overview))

# 1. У какого фильма из списка самый большой бюджет?

In [6]:
answers['1'] = '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)'

In [7]:
data[data.budget == data.budget.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,...,6.3,2011,641683000,"[Johnny Depp, PenÃ©lope Cruz, Geoffrey Rush, I...","[Adventure, Action, Fantasy]",[Rob Marshall],"[Walt Disney Pictures, Jerry Bruckheimer Films...",5,43,411

ВАРИАНТ 2

In [8]:
# сортируем весь DataFrame по столбцу 'budget' (по убыванию)
data.sort_values(by = 'budget', ascending = False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,...,6.3,2011,641683000,"[Johnny Depp, PenÃ©lope Cruz, Geoffrey Rush, I...","[Adventure, Action, Fantasy]",[Rob Marshall],"[Walt Disney Pictures, Jerry Bruckheimer Films...",5,43,411

# 2. Какой из фильмов самый длительный (в минутах)?

In [9]:
answers['2'] = '2. Gods and Generals (tt0279111)'

In [10]:
data[data.runtime == data.runtime.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,...,5.8,2003,-43076064,"[Stephen Lang, Jeff Daniels, Robert Duvall, Ke...","[Drama, History, War]",[Ronald F. Maxwell],"[Turner Pictures, Antietam Filmworks]",2,17,307

# 3. Какой из фильмов самый короткий (в минутах)?

In [11]:
answers['3'] = '3. Winnie the Pooh (tt1449283)'

In [12]:
data[data.runtime == data.runtime.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,...,6.8,2011,-15540000,"[Jim Cummings, Travis Oates, Jim Cummings, Bud...","[Animation, Family]","[Stephen Anderson, Don Hall]","[Walt Disney Pictures, Walt Disney Animation S...",4,15,305

# 4. Какова средняя длительность фильмов?

In [13]:
answers['4'] = '2. 110'

In [14]:
round(data.runtime.mean())

110

# 5. Каково медианное значение длительности фильмов?

In [15]:
answers['5'] = '1. 107'

In [16]:
round(data.runtime.median())

107

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [17]:
answers['6'] = '5. Avatar (tt0499549)'

In [18]:
data[data.profit == data.profit.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,...,7.1,2009,2544505847,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Action, Adventure, Fantasy, Science Fiction]",[James Cameron],"[Ingenious Film Partners, Twentieth Century Fo...",12,6,175

# 7. Какой фильм самый убыточный?

In [19]:
answers['7'] = '5. The Lone Ranger (tt1210819)'

In [20]:
data[data.profit == data.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,...,6.0,2013,-165710090,"[Johnny Depp, Armie Hammer, William Fichtner, ...","[Action, Adventure, Western]",[Gore Verbinski],"[Walt Disney Pictures, Jerry Bruckheimer Films...",7,15,386

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [21]:
answers['8'] = '1. 1478'

In [22]:
len(data[data.revenue > data.budget])

1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [23]:
answers['9'] = '4. The Dark Knight (tt0468569)'

In [24]:
# отсортируем фильмы 2008 года по выручке по убыванию
data[data.release_year == 2008].sort_values(by = 'revenue', ascending = False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,...,8.1,2008,816921825,"[Christian Bale, Michael Caine, Heath Ledger, ...","[Drama, Action, Crime, Thriller]",[Christopher Nolan],"[DC Comics, Legendary Pictures, Warner Bros., ...",7,15,396

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [25]:
answers['10'] = '5. The Lone Ranger (tt1210819)'

In [26]:
# выделим фильмы с 2012 по 2014 г (включительно) и затем отсортируем по прибыли
data.query('2012 <= release_year <= 2014').sort_values(by = 'profit').head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,...,6.0,2013,-165710090,"[Johnny Depp, Armie Hammer, William Fichtner, ...","[Action, Adventure, Western]",[Gore Verbinski],"[Walt Disney Pictures, Jerry Bruckheimer Films...",7,15,386

# 11. Какого жанра фильмов больше всего?

In [27]:
answers['11'] = '3. Drama'

In [28]:
# На преобразованную колонку "genres" применим метод .explode(), который 
# "копирует" значения индекса. Затем произведем подсчет жанров
data.explode('list_of_genres').list_of_genres.value_counts()

Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
Name: list_of_genres, dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [29]:
answers['12'] = '1. Drama'

In [30]:
# Применим действия из вопроса 11, но уже на датасет, в котором только прибыльные фильмы
data[data.profit > 0].explode('list_of_genres').list_of_genres.value_counts()

Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
Name: list_of_genres, dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [31]:
answers['13'] = '5. Peter Jackson'

In [32]:
# Сначала необходимо применить метод .explode() на преобразованную колонку 
# "list_of_director", чтобы разделить совместные работы. Затем сгруппируем
#  по режиссерам, подсчитаем сумму кассовых сборов  и отсортируем
data.explode('list_of_director').groupby(['list_of_director'])['revenue']\
.sum().sort_values(ascending = False)

list_of_director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 997, dtype: int64

# 14. Какой режиссер снял больше всего фильмов в стиле Action?

In [33]:
answers['14'] = '3. Robert Rodriguez'

In [34]:
# Выделим из датасета все фильмы, относящиеся к жанру "Action", замет применим метод 
# .explode() на преобразованную колонку режиссеров и подсчитаем значения
data[data.genres.str.contains('Action')].explode('list_of_director')\
.list_of_director.value_counts()

Robert Rodriguez      9
Michael Bay           7
Paul W.S. Anderson    7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Dave Meyers           1
Trey Parker           1
Peter Segal           1
Stephen Norrington    1
Joe Cornish           1
Name: list_of_director, Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [35]:
answers['15'] = '3. Chris Hemsworth'

In [36]:
data[data.release_year == 2012].explode('list_of_cast').groupby('list_of_cast')\
.revenue.sum().sort_values(ascending = False)

list_of_cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [37]:
answers['16'] = '3. Matt Damon'

In [38]:
data[data.budget > data.budget.mean()].explode('list_of_cast')\
.list_of_cast.value_counts()

Matt Damon               18
Adam Sandler             17
Angelina Jolie           16
Tom Cruise               15
Samuel L. Jackson        15
                         ..
Laurie Holden             1
AdriÃ¡n Alonso Barona     1
Elisabeth Shue            1
Olivia Williams           1
Luis Tosar                1
Name: list_of_cast, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [39]:
answers['17'] = '2. Action'

In [40]:
data[data.cast.str.contains('Nicolas Cage')].explode('list_of_genres')\
.list_of_genres.value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Family              3
Mystery             3
Animation           3
History             2
Horror              1
War                 1
Romance             1
Name: list_of_genres, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [41]:
answers['18'] = '1. K-19: The Widowmaker (tt0267626)'

In [42]:
data[data.production_companies.str.contains('Paramount Pictures')]\
.sort_values(by = 'profit').head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,...,vote_average,release_year,profit,list_of_cast,list_of_genres,list_of_director,list_of_production_companies,release_month,title_length,overview_length
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,...,6.0,2002,-64831034,"[Harrison Ford, Liam Neeson, Peter Sarsgaard, ...","[Thriller, Drama, History]",[Kathryn Bigelow],"[Paramount Pictures, Intermedia Films, Nationa...",7,20,140

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [43]:
answers['19'] = '5. 2015'

In [44]:
data.groupby(['release_year']).revenue.sum().sort_values(ascending = False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [45]:
answers['20'] = '1. 2014'

In [46]:
# Выделим фильмы, в которых принимала участие студия "Warner Bros", затем
# сгруппируем по году выпуска, посчитаем суммарную прибыль и отсортируем
data[data.production_companies.str.contains('Warner Bros')]\
.groupby(['release_year']).profit.sum().sort_values(ascending = False)

release_year
2014    2295464519
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1855493377
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1343545668
2012    1258020056
2002    1022709901
2015     870368348
2006     620170743
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [47]:
answers['21'] = '4. Сентябрь'

In [48]:
data.release_month.value_counts()

9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
Name: release_month, dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [49]:
answers['22'] = '2. 450'

In [50]:
# Выведем летние месяцы столбеца release_month (см. Предобработка)
len(data.query('release_month == (6,7,8)'))

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [51]:
answers['23'] = '5. Peter Jackson'

In [52]:
# Выведем зимние месяцы, применим .explode, тем самым разделяя совместые работы
# режиссеров и произведем их подсчет
data.query('release_month == (1,2,12)').explode('list_of_director')\
.list_of_director.value_counts()

Peter Jackson        7
Clint Eastwood       6
Steven Soderbergh    6
Shawn Levy           4
Martin Scorsese      4
                    ..
Stefen Fangmeier     1
Frank Marshall       1
Tyler Gillett        1
Jay Chandrasekhar    1
Len Wiseman          1
Name: list_of_director, Length: 358, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [53]:
answers['24'] = '5. Four By Two Productions'

In [54]:
data.explode('list_of_production_companies').groupby('list_of_production_companies')\
.title_length.mean().sort_values(ascending = False)

list_of_production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Museum Canada Productions     46.0
Polsky Films                  46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Global Entertainment Group     2.0
Name: title_length, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [55]:
answers['25'] = '3. Midnight Picture Show'

In [56]:
data.explode('list_of_production_companies').groupby('list_of_production_companies')\
.overview_length.mean().sort_values(ascending = False)

list_of_production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview_length, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу?

In [57]:
answers['26'] = '1. Inside Out, The Dark Knight, 12 Years a Slave'

In [58]:
# Отсортируем фильмы по выставленным им оценкам и выведем 1% от общего числа
data.sort_values(by = 'vote_average',ascending = False)\
.head(round(len(data)*0.01))['original_title']

599                                   The Dark Knight
118                                      Interstellar
125                                The Imitation Game
9                                          Inside Out
34                                               Room
1183                          The Wolf of Wall Street
128                                         Gone Girl
1191                                 12 Years a Slave
119                           Guardians of the Galaxy
1081    The Lord of the Rings: The Return of the King
1800                                          Memento
370                                         Inception
872                                       The Pianist
138                          The Grand Budapest Hotel
1188                                              Her
28                                          Spotlight
124                                        Big Hero 6
177                            The Fault in Our Stars
863             The Lord of the Rings: The Two Towers
Name: original_title, dtype: object

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [59]:
answers['27'] = '5. Daniel Radcliffe & Rupert Grint'

In [60]:
data['pairs'] = data.list_of_cast.apply(lambda x: list(combinations(x, 2)))
data.explode('pairs').pairs.value_counts()

(Daniel Radcliffe, Emma Watson)           8
(Daniel Radcliffe, Rupert Grint)          8
(Rupert Grint, Emma Watson)               7
(Ben Stiller, Owen Wilson)                6
(Johnny Depp, Helena Bonham Carter)       6
                                         ..
(Michelle Rodriguez, Lindsay Lohan)       1
(Freddie Highmore, Mary-Louise Parker)    1
(Jake Thomas, Jude Law)                   1
(Geoffrey Rush, Guy Pearce)               1
(Brad Pitt, Julia Ormond)                 1
Name: pairs, Length: 18121, dtype: int64

# Submission

In [61]:
# Список ответов на все вопросы
answers

{'1': '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': '2. Gods and Generals (tt0279111)',
 '3': '3. Winnie the Pooh (tt1449283)',
 '4': '2. 110',
 '5': '1. 107',
 '6': '5. Avatar (tt0499549)',
 '7': '5. The Lone Ranger (tt1210819)',
 '8': '1. 1478',
 '9': '4. The Dark Knight (tt0468569)',
 '10': '5. The Lone Ranger (tt1210819)',
 '11': '3. Drama',
 '12': '1. Drama',
 '13': '5. Peter Jackson',
 '14': '3. Robert Rodriguez',
 '15': '3. Chris Hemsworth',
 '16': '3. Matt Damon',
 '17': '2. Action',
 '18': '1. K-19: The Widowmaker (tt0267626)',
 '19': '5. 2015',
 '20': '1. 2014',
 '21': '4. Сентябрь',
 '22': '2. 450',
 '23': '5. Peter Jackson',
 '24': '5. Four By Two Productions',
 '25': '3. Midnight Picture Show',
 '26': '1. Inside Out, The Dark Knight, 12 Years a Slave',
 '27': '5. Daniel Radcliffe & Rupert Grint'}

In [62]:
# Убедимся, что все вопросы учитаны в answers
len(answers)

27